import Exercise from '@/components/Exercise'
import Head from 'next/head'
import { supabase } from '../../lib/supabaseClient';

function Home({ exercises }: any) {
  return (
    <>
      <Head>
        <title>Gym Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
        <meta name="theme-color" content="#000" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/favicon.png"></link>
      </Head>
      <main className="p-2">
        <h1 className="text-3xl font-bold">Gym Log</h1>
        <div>

          <ul>
            {exercises.map((exercises: any) => (
              <Exercise
                key={exercises.id}
                id={exercises.id}
                defaultExerciseName={exercises.name}
                defaultMax={exercises.max}
                defaultReps={exercises.reps}
                defaultSets={exercises.sets}
              />
            ))}
          </ul>

        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  let { data } = await supabase.from('exercises').select()

  return {
    props: {
      exercises: data
    },
  }
}

export default Home;
